"""removed link column

Revision ID: 386a7235ecef
Revises: 4923464af32d
Create Date: 2022-12-04 17:09:40.911755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386a7235ecef'
down_revision = '4923464af32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('userId', sa.String(length=20), nullable=False),
    sa.Column('user_review', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
