"""added recommendation column

Revision ID: 52efe5f7e028
Revises: 87d985395a15
Create Date: 2022-12-05 17:14:49.622116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52efe5f7e028'
down_revision = '87d985395a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('review')

    # ### end Alembic commands ###
