"""added recommendation column

Revision ID: 59494e46781b
Revises: 52efe5f7e028
Create Date: 2022-12-05 17:16:50.131547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59494e46781b'
down_revision = '52efe5f7e028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation', sa.String(length=20), nullable=True))
        batch_op.drop_column('review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('recommendation')

    # ### end Alembic commands ###
