"""updated date column

Revision ID: d173e72f1f5f
Revises: 
Create Date: 2022-12-04 16:20:39.811256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd173e72f1f5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateadded', sa.DateTime(), nullable=True))
        batch_op.drop_column('dateaddes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateaddes', sa.DATETIME(), nullable=True))
        batch_op.drop_column('dateadded')

    # ### end Alembic commands ###
