"""empty message

Revision ID: 277dea75dd17
Revises: 2910a7c4da80
Create Date: 2022-12-07 02:41:32.960502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277dea75dd17'
down_revision = '2910a7c4da80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_e')
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.alter_column('imageName',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['mobile'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.alter_column('imageName',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('t_e',
    sa.Column('docs', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
