"""updated added rating column

Revision ID: 38e707558de5
Revises: d173e72f1f5f
Create Date: 2022-12-04 16:45:56.115762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e707558de5'
down_revision = 'd173e72f1f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
