"""removed link column

Revision ID: 5bc1bf4520d8
Revises: f252359fbb04
Create Date: 2022-12-04 16:59:19.065898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc1bf4520d8'
down_revision = 'f252359fbb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userIdId', sa.String(length=20), nullable=False))
        batch_op.drop_column('userId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('userIdId')

    # ### end Alembic commands ###
