"""added recommendation column

Revision ID: 698e76979cc0
Revises: aa0f92d2eba5
Create Date: 2022-12-07 03:39:16.001963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698e76979cc0'
down_revision = 'aa0f92d2eba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('userId',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
