"""removed link column

Revision ID: 769adafe8d70
Revises: 386a7235ecef
Create Date: 2022-12-04 17:10:50.513471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769adafe8d70'
down_revision = '386a7235ecef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=200), nullable=True))
        batch_op.drop_column('user_review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_review', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('user')

    # ### end Alembic commands ###
