"""added recommendation column

Revision ID: c164108bbff5
Revises: 277dea75dd17
Create Date: 2022-12-07 03:12:51.891152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c164108bbff5'
down_revision = '277dea75dd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_info', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
